# Generated by Django 4.2.30 on 2026-06-19 23:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('medias', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageWeb',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=300)),
                ('url', models.CharField(max_length=500)),
                ('date_publication', models.DateField()),
                ('auteur', models.CharField(blank=True, max_length=150, null=True)),
                ('duree_contenu', models.IntegerField(blank=True, help_text='Durée du contenu en secondes (audio/vidéo uniquement)', null=True)),
                ('media', models.ForeignKey(db_column='media_id', on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='medias.media')),
            ],
            options={
                'verbose_name': 'Page web',
                'verbose_name_plural': 'Pages web',
                'db_table': 'pages_page_web',
                'ordering': ['-date_publication'],
            },
        ),
    ]
