# Generated by Django 4.2.30 on 2026-06-19 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evenement',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('type_even', models.CharField(choices=[('clic', 'Clic'), ('scroll', 'Scroll'), ('lecture', 'Lecture (audio)'), ('visionnage', 'Visionnage (vidéo)')], max_length=50)),
                ('date_heure', models.DateTimeField()),
                ('duree_ecoute', models.IntegerField(blank=True, help_text='Secondes', null=True)),
                ('profondeur_scroll', models.IntegerField(blank=True, help_text='0 à 100 (%)', null=True)),
            ],
            options={
                'verbose_name': 'Événement',
                'verbose_name_plural': 'Événements',
                'db_table': 'evenements_evenement',
                'ordering': ['-date_heure'],
            },
        ),
        migrations.CreateModel(
            name='Visiteur',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('adresse_ip', models.CharField(max_length=45)),
                ('type_appareil', models.CharField(choices=[('mobile', 'Mobile'), ('desktop', 'Desktop'), ('tablette', 'Tablette')], max_length=50)),
                ('os', models.CharField(blank=True, max_length=50, null=True)),
                ('navigateur', models.CharField(blank=True, max_length=100, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('source_trafic', models.CharField(blank=True, choices=[('recherche', 'Recherche organique'), ('direct', 'Direct'), ('reseaux_sociaux', 'Réseaux sociaux'), ('autres', 'Autres')], max_length=30, null=True)),
            ],
            options={
                'verbose_name': 'Visiteur',
                'verbose_name_plural': 'Visiteurs',
                'db_table': 'evenements_visiteur',
            },
        ),
    ]
