# Generated by Django 4.2.30 on 2026-06-19 23:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('evenements', '0001_initial'),
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='evenement',
            name='page',
            field=models.ForeignKey(db_column='page_id', on_delete=django.db.models.deletion.CASCADE, related_name='evenements', to='pages.pageweb'),
        ),
        migrations.AddField(
            model_name='evenement',
            name='visiteur',
            field=models.ForeignKey(db_column='visiteur_id', on_delete=django.db.models.deletion.CASCADE, related_name='evenements', to='evenements.visiteur'),
        ),
        migrations.AddIndex(
            model_name='evenement',
            index=models.Index(fields=['date_heure'], name='evenements__date_he_e2cc4f_idx'),
        ),
        migrations.AddIndex(
            model_name='evenement',
            index=models.Index(fields=['type_even'], name='evenements__type_ev_6f4be1_idx'),
        ),
        migrations.AddIndex(
            model_name='evenement',
            index=models.Index(fields=['page', 'date_heure'], name='evenements__page_id_20929a_idx'),
        ),
    ]
