# Generated by Django 4.2.30 on 2026-06-19 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=200)),
                ('url', models.CharField(max_length=200, unique=True)),
                ('type_media', models.CharField(choices=[('presse', 'Presse'), ('television', 'Télévision'), ('radio', 'Radio'), ('web', 'Web')], max_length=50)),
                ('statut', models.CharField(choices=[('actif', 'Actif'), ('inactif', 'Inactif'), ('supprime', 'Supprimé')], default='actif', max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Média',
                'verbose_name_plural': 'Médias',
                'db_table': 'medias_media',
                'ordering': ['nom'],
            },
        ),
    ]
