# Generated by Django 4.2.30 on 2026-06-19 23:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('medias', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='gestionnaire',
            field=models.ForeignKey(blank=True, db_column='gestionnaire_id', limit_choices_to={'role': 'gestionnaire'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medias_geres', to=settings.AUTH_USER_MODEL),
        ),
    ]
