# Generated by Django 4.2.30 on 2026-06-19 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rapport',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('type_rapport', models.CharField(choices=[('media', 'Par média'), ('global', 'Global (multi-médias)')], max_length=20)),
                ('periode_debut', models.DateField()),
                ('periode_fin', models.DateField()),
                ('inclure_graphiques', models.BooleanField(default=True)),
                ('inclure_stats', models.BooleanField(default=True)),
                ('stats', models.JSONField(blank=True, default=dict)),
                ('statut', models.CharField(choices=[('en_cours', 'En cours'), ('pret', 'Prêt'), ('erreur', 'Erreur')], default='en_cours', max_length=20)),
                ('date_generation', models.DateTimeField(auto_now_add=True)),
                ('timeout_secondes', models.IntegerField(default=120)),
                ('message_erreur', models.CharField(blank=True, max_length=255, null=True)),
                ('fichier_pdf', models.FileField(blank=True, null=True, upload_to='rapports/')),
            ],
            options={
                'verbose_name': 'Rapport',
                'verbose_name_plural': 'Rapports',
                'db_table': 'rapports_rapport',
                'ordering': ['-date_generation'],
            },
        ),
    ]
