# Generated by Django 4.2.30 on 2026-06-19 23:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rapports', '0001_initial'),
        ('medias', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rapport',
            name='genere_par',
            field=models.ForeignKey(db_column='genere_par_id', on_delete=django.db.models.deletion.CASCADE, related_name='rapports_generes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rapport',
            name='media',
            field=models.ForeignKey(blank=True, db_column='media_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rapports', to='medias.media'),
        ),
    ]
